### ISSUE TITLE
Conflict with climate mod

### ISSUE THREAD

**Issue by IFRFSX** [aa6/minetest_wadsprint#4]

**Comment by aa6** [comment]
Could you provide a link to the climate mod please?

**Comment by aa6** [comment]
Could you provide a link to the climate mod please?

**Comment by aa6** [comment]
Could you provide a link to the climate mod please?

**Comment by aa6** [comment]
Could you provide a link to the climate mod please?

**Comment by aa6** [comment]
Could you provide a link to the climate mod please?

**Comment by aa6** [comment]
Could you provide a link to the climate mod please?

**Comment by aa6** [comment]
Could you provide a link to the climate mod please?

**Comment by aa6** [comment]
Could you provide a link to the climate mod please?

**Comment by aa6** [comment]
Could you provide a link to the climate mod please?

**Comment by aa6** [comment]
Could you provide a link to the climate mod please?

**Comment by aa6** [comment]
Could you provide a link to the climate mod please?

**Comment by IFRFSX** [comment]
https://github.com/t-affeldt/climate_api
https://github.com/t-affeldt/regional_weather

conflict appear from regional_weather, climate_api is it's depend.

**Comment by IFRFSX** [comment]
The problem is simple: <climate_api> is an api, and its author also made a <regional_weather>, which are all part of the [climate integration package](https://github.com/t-affeldt/climate "link").
When <regional_weather> is turned on, it will cause <WADSprint> and an old mod called <Sprint> to not work when in use (the other four mods will not be turned on and will not affect), so please try to improve your works, Avoid this conflict.

**Comment by aa6** [comment]
Well I have created a new world and added only two mods: `regional_weather` and `climate_api`. And the game crashed with an error

> ServerError: AsyncErr: environment_Step: Runtime error from mod 'climate_api' in callback environment_Step(): ...est/mods/regional_weather-master/ca_weathers/ambient.lua:60: attempt to call field 'dot' (a nil value)
> ERROR[Main]: stack traceback:
> ERROR[Main]:   ...est/mods/regional_weather-master/ca_weathers/ambient.lua:60: in function 'effects'
> ERROR[Main]:   /home/me/.minetest/mods/climate_api-master/lib/trigger.lua:74: in function 'get_weather_effects'
> ERROR[Main]:   /home/me/.minetest/mods/climate_api-master/lib/trigger.lua:109: in function 'get_active_effects'
> ERROR[Main]:   /home/me/.minetest/mods/climate_api-master/lib/main.lua:38: in function </home/me/.minetest/mods/climate_api-master/lib/main.lua:15>
> ERROR[Main]:   /usr/share/minetest/builtin/game/register.lua:419: in function </usr/share/minetest/builtin/game/register.lua:399>
> ERROR[Main]: stack traceback:

Are you sure this has anything to do with `minetest_wadsprint` mod?

**Comment by IFRFSX** [comment]
I loaded the entire <climate> package (five mods) into the game, and then turned on wadsprint. As a result, climate worked normally, but wadsprint had no effect.

**Comment by IFRFSX** [comment]
[climate_and_wadsprint.mkv.zip](https://github.com/aa6/minetest_wadsprint/files/5172958/climate_and_wadsprint.mkv.zip)

**Comment by aa6** [comment]
I'm sorry to ask, but how did you exactly downloaded the modpack? I can't figure it out. When I'm downloading it via github as a zip archive, the mod subdirectories are empty. And when I download them separately and exact versions which are stated in the github, I'm getting the same error again. Could you upload your archive of climate modpack or tell what exact versions of mods you are using?

**Comment by IFRFSX** [comment]
Do not download the version marked by modpack, please download the latest version!

In fact, it’s okay if you only open the two mods. I can also run them here, but I don’t know how your bug appears. I’ll upload my package and upload it to you.
[climate.zip](https://github.com/aa6/minetest_wadsprint/files/5186095/climate.zip)

**Comment by aa6** [comment]
I tried your archive and it don't works too. So I suggest you to install `monoids` mod https://github.com/minetest-mods/player_monoids which is an intermediate API for player physics changing. Both climate and wadsprint seems to support `monoids` so installing and enabling it this should resolve the problem.

**Comment by IFRFSX** [comment]
The problem is solved, thank you for your help.
