### ISSUE TITLE
Inquiry #2

### ISSUE THREAD

**Issue by cyromaniac** [aa6/minetest_wadsprint#7]
Hey, thank you for your response on my last ticket. Buying and selling Minecraft accounts isn’t “illegal”, it just goes against Mojang terms of service. The only consequence there would be is Mojang temporarily/permanently locking the Minecraft account, it’s not super common though and I’m willing to take the risk. I have been an avid Minecraft player for over a decade now, and have always dreamed of owning a 2 character username. I understand your disliking for Minecraft, but I still enjoy the game and play everyday. I'd also like to mention, I'd be willing to offer you $500.00 USD for the account if you would be willing to let it go.

**Comment by cyromaniac** [comment]
I'd also like to mention, I'd be willing to offer you $500.00 USD for the account if you would be willing to let it go.

**Comment by aa6** [comment]
Well, what's your email?

**Comment by cyromaniac** [comment]
My email is cyromcnetwork@gmail.com, thanks for the quick response once again.

**Comment by aa6** [comment]
I have sent you an email. Please check.
